apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchid.fullname" . }}-backend
spec:
  ports:
    - name: http
      targetPort: 8081
      protocol: TCP
      port: 8081
  selector:
    {{- include "matchid.backend.selectorLabels" . | nindent 4 }}
