apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matchid.fullname" . }}-backend
spec:
  selector:
    matchLabels: {{- include "matchid.backend.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "matchid.fullname" . }}-backend
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "matchid.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: matchid-backend
          image: "{{ .Values.image.repository }}-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-configmap
          volumeMounts:
            - name: disque-matchid
              mountPath: /matchID/projects
  volumeClaimTemplates:
    - metadata:
        name: disque-matchid
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
