apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "matchid.elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matchid.elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node