apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchid.elasticsearch.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    {{- include "matchid.elasticsearch.selectorLabels" . | nindent 4 }}