apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchid.fullname" . }}-frontend
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
  {{- include "matchid.frontend.selectorLabels" . | nindent 4 }}
