apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matchid.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "matchid.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matchid.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: matchid-frontend
          image: "{{ .Values.image.repository }}-frontend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-frontend-configmap
          env:
            - name: BACKEND_HOST
              value: "{{ include "matchid.fullname" . }}-backend"