apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchid-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: matchid-frontend
  template:
    metadata:
      labels:
        component: matchid-frontend
    spec:
      containers:
        - name: matchid-frontend
          image: matchid/matchid-frontend
          ports:
            - containerPort: 80
          env:
            - name: API_PATH
              value: /matchID/api/v0
            - name: BACKEND_PORT
              value: '8081'
            - name: BACKEND_HOST
              value: matchid-backend-service
            - name: API_USER_LIMIT_RATE
              value: '1r/s'
            - name: API_DOWNLOAD_LIMIT_RATE
              value: '30r/m'
            - name: API_USER_BURST
              value: '20 nodelay'
            - name: API_USER_SCOPE
              value: 'http_x_forwarded_for'
            - name: API_GLOBAL_LIMIT_RATE
              value: '20r/s'
            - name: API_GLOBAL_BURST
              value: '200 nodelay'
            - name: APP_NAME
              value: matchID
