apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.image.name }}-statefulset
spec:
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.readReplicas.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.image.port }}
          envFrom:
            - configMapRef:
                name: back-configmap
          volumeMounts:
            - name: disque-matchid
              mountPath: /matchID/projects
  volumeClaimTemplates:
    - metadata:
        name: disque-matchid
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
