apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service
spec:
  ports:
    - name: http
      targetPort: {{ .Values.image.port }}
      port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.image.name }}
